version: "3.8"

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

    environment:
      - DB_HOST=db
      - DB_USER=wowperf_user
      - DB_PASSWORD=wowperf
      - DB_NAME=wowperf_db
      - DB_SSL_MODE=disable
      - REDIS_URL=redis:6379
    volumes:
      - ./backend/data/static:/app/static
  db:
    image: postgres:15.3
    environment:
      - POSTGRES_USER=wowperf_user
      - POSTGRES_PASSWORD=wowperf
      - POSTGRES_DB=wowperf_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wowperf_user -d wowperf_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    environment:
      - ADMINER_DEFAULT_SERVER=db

volumes:
  postgres_data:
  redis_data:
