version: "3.8"

services:
  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: runner
    volumes:
      - ./frontend:/app:cached
      - frontend_node_modules:/app/node_modules:delegated
      - frontend_next:/app/.next:delegated
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
    depends_on:
      - backend

  # Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development # Use the development stage
    volumes:
      - ./backend:/app:cached # Mount the source code for hot-reloading
      - backend_go:/go:delegated # Persistent cache for Go modules
    environment:
      - DB_HOST=db
      - DB_USER=wowperf_user
      - DB_PASSWORD=wowperf
      - DB_NAME=wowperf_db
      - DB_SSL_MODE=disable
      - REDIS_URL=redis:6379
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  # Database Postgres
  db:
    image: postgres:15.3
    environment:
      - POSTGRES_USER=wowperf_user
      - POSTGRES_PASSWORD=wowperf
      - POSTGRES_DB=wowperf_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wowperf_user -d wowperf_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Adminer
  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"

volumes:
  postgres_data:
  redis_data:
  frontend_node_modules:
  frontend_next:
  backend_go:
