-- 001_initial_tables.down.sql
DROP TABLE IF EXISTS season_dungeons CASCADE;
DROP TABLE IF EXISTS key_stone_upgrades CASCADE;
DROP TABLE IF EXISTS affixes CASCADE;
DROP TABLE IF EXISTS raids CASCADE;
DROP TABLE IF EXISTS dungeons CASCADE;
DROP TABLE IF EXISTS seasons CASCADE;
DROP TABLE IF EXISTS users CASCADE;