global:
  resolve_timeout: 5m

route:
  group_by: ["alertname", "job"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: "discord"

receivers:
  - name: "discord"
    discord_configs:
      - webhook_url: "{{ discord_webhook_url }}"
        title: '{{ template "discord.title" . }}'
        message: '{{ template "discord.message" . }}'

templates:
  - "/etc/alertmanager/templates/*.tmpl"
