export const asiaRealms = [
  // Korean Realms
  { id: 514, name: "가로나", slug: "garona", region: "KR" },
  { id: 515, name: "굴단", slug: "guldan", region: "KR" },
  { id: 516, name: "노르간논", slug: "norgannon", region: "KR" },
  { id: 517, name: "달라란", slug: "dalaran", region: "KR" },
  { id: 518, name: "데스윙", slug: "deathwing", region: "KR" },
  { id: 519, name: "듀로탄", slug: "durotan", region: "KR" },
  { id: 520, name: "라그나로스", slug: "hellscream", region: "KR" },
  { id: 521, name: "렉사르", slug: "rexxar", region: "KR" },
  { id: 522, name: "말퓨리온", slug: "malfurion", region: "KR" },
  { id: 523, name: "불타는 군단", slug: "burning-legion", region: "KR" },
  { id: 524, name: "세나리우스", slug: "cenarius", region: "KR" },
  { id: 525, name: "스톰레이지", slug: "stormrage", region: "KR" },
  { id: 526, name: "아즈샤라", slug: "azshara", region: "KR" },
  { id: 527, name: "알렉스트라자", slug: "alexstrasza", region: "KR" },
  { id: 528, name: "에이그윈", slug: "aegwynn", region: "KR" },
  { id: 529, name: "엘룬", slug: "elune", region: "KR" },
  { id: 530, name: "와일드해머", slug: "wildhammer", region: "KR" },
  { id: 531, name: "윈드러너", slug: "windrunner", region: "KR" },
  { id: 532, name: "줄진", slug: "zuljin", region: "KR" },
  { id: 533, name: "하이잘", slug: "hyjal", region: "KR" },
  { id: 534, name: "헬스크림", slug: "hellscream", region: "KR" },

  // Taiwan Realms
  { id: 537, name: "世界之樹", slug: "world-tree", region: "TW" },
  { id: 538, name: "亞雷戈斯", slug: "arygos", region: "TW" },
  { id: 539, name: "冰霜之刺", slug: "frostmane", region: "TW" },
  { id: 540, name: "冰風崗哨", slug: "chillwind-point", region: "TW" },
  { id: 541, name: "地獄吼", slug: "hellscream", region: "TW" },
  { id: 542, name: "夜空之歌", slug: "nightsong", region: "TW" },
  { id: 543, name: "天空之牆", slug: "skywall", region: "TW" },
  { id: 544, name: "寒冰皇冠", slug: "icecrown", region: "TW" },
  { id: 545, name: "尖石", slug: "spirestone", region: "TW" },
  { id: 546, name: "屠魔山谷", slug: "demon-fall-canyon", region: "TW" },
  { id: 547, name: "憤怒使者", slug: "wrathbringer", region: "TW" },
  { id: 548, name: "日落沼澤", slug: "sundown-marsh", region: "TW" },
  { id: 549, name: "暗影之月", slug: "shadowmoon", region: "TW" },
  { id: 550, name: "水晶之刺", slug: "crystalpine-stinger", region: "TW" },
  { id: 551, name: "狂熱之刃", slug: "zealot-blade", region: "TW" },
  { id: 552, name: "眾星之子", slug: "queldorei", region: "TW" },
  { id: 553, name: "米奈希爾", slug: "menethil", region: "TW" },
  { id: 554, name: "聖光之願", slug: "lights-hope", region: "TW" },
  { id: 555, name: "血之谷", slug: "bleeding-hollow", region: "TW" },
  { id: 556, name: "語風", slug: "whisperwind", region: "TW" },
  { id: 557, name: "銀翼要塞", slug: "silverwing-hold", region: "TW" },
  { id: 558, name: "阿薩斯", slug: "arthas", region: "TW" },
  { id: 559, name: "雷鱗", slug: "stormscale", region: "TW" },
  { id: 905, name: "巨龍之喉", slug: "dragonmaw", region: "TW" },
  { id: 907, name: "雲蛟衛", slug: "order-of-the-cloud-serpent", region: "TW" },
  { id: 927, name: "克羅之刃", slug: "krol-blade", region: "TW" },
  { id: 928, name: "老馬布蘭契", slug: "old-blanchy", region: "TW" },
];
