// euRealmsMapping.ts

export const euRealms = [
  // English Realms
  { id: 247, name: "Aerie Peak", slug: "aerie-peak", region: "EU" },
  { id: 248, name: "Agamaggan", slug: "agamaggan", region: "EU" },
  { id: 249, name: "Aggramar", slug: "aggramar", region: "EU" },
  { id: 250, name: "Ahn'Qiraj", slug: "ahnqiraj", region: "EU" },
  { id: 251, name: "Al'Akir", slug: "alakir", region: "EU" },
  { id: 252, name: "Alonsus", slug: "alonsus", region: "EU" },
  { id: 253, name: "Anachronos", slug: "anachronos", region: "EU" },
  { id: 254, name: "Arathor", slug: "arathor", region: "EU" },
  { id: 255, name: "Argent Dawn", slug: "argent-dawn", region: "EU" },
  { id: 256, name: "Aszune", slug: "aszune", region: "EU" },
  { id: 257, name: "Auchindoun", slug: "auchindoun", region: "EU" },
  { id: 258, name: "Azjol-Nerub", slug: "azjolnerub", region: "EU" },
  { id: 259, name: "Azuremyst", slug: "azuremyst", region: "EU" },
  { id: 260, name: "Balnazzar", slug: "balnazzar", region: "EU" },
  { id: 261, name: "Blade's Edge", slug: "blades-edge", region: "EU" },
  { id: 262, name: "Bladefist", slug: "bladefist", region: "EU" },
  { id: 263, name: "Bloodfeather", slug: "bloodfeather", region: "EU" },
  { id: 264, name: "Bloodhoof", slug: "bloodhoof", region: "EU" },
  { id: 265, name: "Bloodscalp", slug: "bloodscalp", region: "EU" },
  { id: 266, name: "Boulderfist", slug: "boulderfist", region: "EU" },
  {
    id: 267,
    name: "Bronze Dragonflight",
    slug: "bronze-dragonflight",
    region: "EU",
  },
  { id: 268, name: "Bronzebeard", slug: "bronzebeard", region: "EU" },
  { id: 269, name: "Burning Blade", slug: "burning-blade", region: "EU" },
  { id: 270, name: "Burning Legion", slug: "burning-legion", region: "EU" },
  { id: 271, name: "Burning Steppes", slug: "burning-steppes", region: "EU" },
  {
    id: 272,
    name: "Chamber of Aspects",
    slug: "chamber-of-aspects",
    region: "EU",
  },
  { id: 273, name: "Chromaggus", slug: "chromaggus", region: "EU" },
  { id: 274, name: "Crushridge", slug: "crushridge", region: "EU" },
  { id: 275, name: "Daggerspine", slug: "daggerspine", region: "EU" },
  { id: 276, name: "Darkmoon Faire", slug: "darkmoon-faire", region: "EU" },
  { id: 277, name: "Darksorrow", slug: "darksorrow", region: "EU" },
  { id: 278, name: "Darkspear", slug: "darkspear", region: "EU" },
  { id: 279, name: "Deathwing", slug: "deathwing", region: "EU" },
  {
    id: 280,
    name: "Defias Brotherhood",
    slug: "defias-brotherhood",
    region: "EU",
  },
  { id: 281, name: "Dentarg", slug: "dentarg", region: "EU" },
  { id: 282, name: "Doomhammer", slug: "doomhammer", region: "EU" },
  { id: 283, name: "Draenor", slug: "draenor", region: "EU" },
  { id: 284, name: "Dragonblight", slug: "dragonblight", region: "EU" },
  { id: 285, name: "Dragonmaw", slug: "dragonmaw", region: "EU" },
  { id: 286, name: "Drak'thul", slug: "drakthul", region: "EU" },
  { id: 287, name: "Dunemaul", slug: "dunemaul", region: "EU" },
  { id: 288, name: "Earthen Ring", slug: "earthen-ring", region: "EU" },
  { id: 289, name: "Emerald Dream", slug: "emerald-dream", region: "EU" },
  { id: 290, name: "Emeriss", slug: "emeriss", region: "EU" },
  { id: 291, name: "Eonar", slug: "eonar", region: "EU" },
  { id: 292, name: "Executus", slug: "executus", region: "EU" },
  { id: 293, name: "Frostmane", slug: "frostmane", region: "EU" },
  { id: 294, name: "Frostwhisper", slug: "frostwhisper", region: "EU" },
  { id: 295, name: "Genjuros", slug: "genjuros", region: "EU" },
  { id: 296, name: "Ghostlands", slug: "ghostlands", region: "EU" },
  { id: 297, name: "Grim Batol", slug: "grim-batol", region: "EU" },
  { id: 298, name: "Hakkar", slug: "hakkar", region: "EU" },
  { id: 299, name: "Haomarush", slug: "haomarush", region: "EU" },
  { id: 300, name: "Hellfire", slug: "hellfire", region: "EU" },
  { id: 301, name: "Hellscream", slug: "hellscream", region: "EU" },
  { id: 302, name: "Jaedenar", slug: "jaedenar", region: "EU" },
  { id: 303, name: "Karazhan", slug: "karazhan", region: "EU" },
  { id: 304, name: "Kazzak", slug: "kazzak", region: "EU" },
  { id: 305, name: "Khadgar", slug: "khadgar", region: "EU" },
  { id: 306, name: "Kilrogg", slug: "kilrogg", region: "EU" },
  { id: 307, name: "Kor'gall", slug: "korgall", region: "EU" },
  { id: 308, name: "Kul Tiras", slug: "kul-tiras", region: "EU" },
  { id: 309, name: "Laughing Skull", slug: "laughing-skull", region: "EU" },
  { id: 310, name: "Lightbringer", slug: "lightbringer", region: "EU" },
  {
    id: 311,
    name: "Lightning's Blade",
    slug: "lightnings-blade",
    region: "EU",
  },
  { id: 312, name: "Magtheridon", slug: "magtheridon", region: "EU" },
  { id: 313, name: "Mazrigos", slug: "mazrigos", region: "EU" },
  { id: 314, name: "Moonglade", slug: "moonglade", region: "EU" },
  { id: 315, name: "Nagrand", slug: "nagrand", region: "EU" },
  { id: 316, name: "Neptulon", slug: "neptulon", region: "EU" },
  { id: 317, name: "Nordrassil", slug: "nordrassil", region: "EU" },
  { id: 318, name: "Outland", slug: "outland", region: "EU" },
  { id: 319, name: "Quel'Thalas", slug: "quelthalas", region: "EU" },
  { id: 320, name: "Ragnaros", slug: "ragnaros", region: "EU" },
  { id: 321, name: "Ravencrest", slug: "ravencrest", region: "EU" },
  { id: 322, name: "Ravenholdt", slug: "ravenholdt", region: "EU" },
  { id: 323, name: "Runetotem", slug: "runetotem", region: "EU" },
  { id: 324, name: "Saurfang", slug: "saurfang", region: "EU" },
  {
    id: 325,
    name: "Scarshield Legion",
    slug: "scarshield-legion",
    region: "EU",
  },
  { id: 326, name: "Shadowsong", slug: "shadowsong", region: "EU" },
  { id: 327, name: "Shattered Halls", slug: "shattered-halls", region: "EU" },
  { id: 328, name: "Shattered Hand", slug: "shattered-hand", region: "EU" },
  { id: 329, name: "Silvermoon", slug: "silvermoon", region: "EU" },
  { id: 330, name: "Skullcrusher", slug: "skullcrusher", region: "EU" },
  { id: 331, name: "Spinebreaker", slug: "spinebreaker", region: "EU" },
  { id: 332, name: "Sporeggar", slug: "sporeggar", region: "EU" },
  {
    id: 333,
    name: "Steamwheedle Cartel",
    slug: "steamwheedle-cartel",
    region: "EU",
  },
  { id: 334, name: "Stormrage", slug: "stormrage", region: "EU" },
  { id: 335, name: "Stormreaver", slug: "stormreaver", region: "EU" },
  { id: 336, name: "Stormscale", slug: "stormscale", region: "EU" },
  { id: 337, name: "Sunstrider", slug: "sunstrider", region: "EU" },
  { id: 338, name: "Sylvanas", slug: "sylvanas", region: "EU" },
  { id: 339, name: "Talnivarr", slug: "talnivarr", region: "EU" },
  { id: 340, name: "Tarren Mill", slug: "tarren-mill", region: "EU" },
  { id: 341, name: "Terenas", slug: "terenas", region: "EU" },
  { id: 342, name: "Terokkar", slug: "terokkar", region: "EU" },
  { id: 343, name: "The Maelstrom", slug: "the-maelstrom", region: "EU" },
  { id: 344, name: "The Sha'tar", slug: "the-shatar", region: "EU" },
  { id: 345, name: "The Venture Co", slug: "the-venture-co", region: "EU" },
  { id: 346, name: "Thunderhorn", slug: "thunderhorn", region: "EU" },
  {
    id: 347,
    name: "Trollbane",
    slug: "trollbane",
    region: "EU",
  },
  {
    id: 348,
    name: "Turalyon",
    slug: "turalyon",
    region: "EU",
  },
  {
    id: 349,
    name: "Twilight's Hammer",
    slug: "twilights-hammer",
    region: "EU",
  },
  {
    id: 350,
    name: "Twisting Nether",
    slug: "twisting-nether",
    region: "EU",
  },
  {
    id: 351,
    name: "Vashj",
    slug: "vashj",
    region: "EU",
  },
  {
    id: 352,
    name: "Vek'nilash",
    slug: "veknilash",
    region: "EU",
  },
  {
    id: 353,
    name: "Wildhammer",
    slug: "wildhammer",
    region: "EU",
  },
  {
    id: 354,
    name: "Xavius",
    slug: "xavius",
    region: "EU",
  },
  {
    id: 355,
    name: "Zenedar",
    slug: "zenedar",
    region: "EU",
  },

  // French Realms
  { id: 356, name: "Arak-arahm", slug: "arakarahm", region: "EU" },
  { id: 357, name: "Arathi", slug: "arathi", region: "EU" },
  { id: 358, name: "Archimonde", slug: "archimonde", region: "EU" },
  { id: 359, name: "Chants éternels", slug: "chants-éternels", region: "EU" },
  { id: 360, name: "Cho'gall", slug: "chogall", region: "EU" },
  {
    id: 361,
    name: "Confrérie du Thorium",
    slug: "confrérie-du-thorium",
    region: "EU",
  },
  {
    id: 362,
    name: "Conseil des Ombres",
    slug: "conseil-des-ombres",
    region: "EU",
  },
  {
    id: 363,
    name: "Culte de la Rive noire",
    slug: "culte-de-la-rive-noire",
    region: "EU",
  },
  { id: 364, name: "Dalaran", slug: "dalaran", region: "EU" },
  { id: 365, name: "Drek'Thar", slug: "drekthar", region: "EU" },
  { id: 366, name: "Eitrigg", slug: "eitrigg", region: "EU" },
  { id: 367, name: "Eldre'Thalas", slug: "eldrethalas", region: "EU" },
  { id: 368, name: "Elune", slug: "elune", region: "EU" },
  { id: 369, name: "Garona", slug: "garona", region: "EU" },
  { id: 370, name: "Hyjal", slug: "hyjal", region: "EU" },
  { id: 371, name: "Illidan", slug: "illidan", region: "EU" },
  { id: 372, name: "Kael'thas", slug: "kaelthas", region: "EU" },
  { id: 373, name: "Khaz Modan", slug: "khaz-modan", region: "EU" },
  { id: 374, name: "Kirin Tor", slug: "kirin-tor", region: "EU" },
  { id: 375, name: "Krasus", slug: "krasus", region: "EU" },
  {
    id: 376,
    name: "La Croisade écarlate",
    slug: "la-croisade-écarlate",
    region: "EU",
  },
  { id: 377, name: "Les Clairvoyants", slug: "les-clairvoyants", region: "EU" },
  { id: 378, name: "Les Sentinelles", slug: "les-sentinelles", region: "EU" },
  {
    id: 379,
    name: "Marécage de Zangar",
    slug: "marécage-de-zangar",
    region: "EU",
  },
  { id: 380, name: "Medivh", slug: "medivh", region: "EU" },
  { id: 381, name: "Naxxramas", slug: "naxxramas", region: "EU" },
  { id: 383, name: "Rashgarroth", slug: "rashgarroth", region: "EU" },
  { id: 384, name: "Sargeras", slug: "sargeras", region: "EU" },
  { id: 385, name: "Sinstralis", slug: "sinstralis", region: "EU" },
  { id: 386, name: "Suramar", slug: "suramar", region: "EU" },
  { id: 387, name: "Temple noir", slug: "temple-noir", region: "EU" },
  { id: 388, name: "Throk'Feroth", slug: "throkferoth", region: "EU" },
  { id: 389, name: "Uldaman", slug: "uldaman", region: "EU" },
  { id: 390, name: "Varimathras", slug: "varimathras", region: "EU" },
  { id: 391, name: "Vol'jin", slug: "voljin", region: "EU" },
  { id: 392, name: "Ysondre", slug: "ysondre", region: "EU" },
  { id: 912, name: "Ner'zhul", slug: "nerzhul", region: "EU" },

  // German Realms
  { id: 393, name: "Aegwynn", slug: "aegwynn", region: "EU" },
  { id: 394, name: "Alexstrasza", slug: "alexstrasza", region: "EU" },
  { id: 395, name: "Alleria", slug: "alleria", region: "EU" },
  { id: 396, name: "Aman'Thul", slug: "amanthul", region: "EU" },
  { id: 397, name: "Ambossar", slug: "ambossar", region: "EU" },
  { id: 398, name: "Anetheron", slug: "anetheron", region: "EU" },
  { id: 399, name: "Antonidas", slug: "antonidas", region: "EU" },
  { id: 400, name: "Anub'arak", slug: "anubarak", region: "EU" },
  { id: 401, name: "Area 52", slug: "area-52", region: "EU" },
  { id: 402, name: "Arthas", slug: "arthas", region: "EU" },
  { id: 403, name: "Arygos", slug: "arygos", region: "EU" },
  { id: 404, name: "Azshara", slug: "azshara", region: "EU" },
  { id: 405, name: "Baelgun", slug: "baelgun", region: "EU" },
  { id: 406, name: "Blackhand", slug: "blackhand", region: "EU" },
  { id: 407, name: "Blackmoore", slug: "blackmoore", region: "EU" },
  { id: 408, name: "Blackrock", slug: "blackrock", region: "EU" },
  { id: 409, name: "Blutkessel", slug: "blutkessel", region: "EU" },
  { id: 410, name: "Dalvengyr", slug: "dalvengyr", region: "EU" },
  { id: 411, name: "Das Konsortium", slug: "das-konsortium", region: "EU" },
  { id: 412, name: "Das Syndikat", slug: "das-syndikat", region: "EU" },
  {
    id: 413,
    name: "Der Abyssische Rat",
    slug: "der-abyssische-rat",
    region: "EU",
  },
  { id: 414, name: "Der Mithrilorden", slug: "der-mithrilorden", region: "EU" },
  {
    id: 415,
    name: "Der Rat von Dalaran",
    slug: "der-rat-von-dalaran",
    region: "EU",
  },
  { id: 416, name: "Destromath", slug: "destromath", region: "EU" },
  { id: 417, name: "Dethecus", slug: "dethecus", region: "EU" },
  { id: 418, name: "Die Aldor", slug: "die-aldor", region: "EU" },
  { id: 419, name: "Die Arguswacht", slug: "die-arguswacht", region: "EU" },
  { id: 420, name: "Die Nachtwache", slug: "die-nachtwache", region: "EU" },
  {
    id: 421,
    name: "Die Silberne Hand",
    slug: "die-silberne-hand",
    region: "EU",
  },
  { id: 422, name: "Die Todeskrallen", slug: "die-todeskrallen", region: "EU" },
  { id: 423, name: "Die ewige Wacht", slug: "die-ewige-wacht", region: "EU" },
  { id: 424, name: "Dun Morogh", slug: "dun-morogh", region: "EU" },
  { id: 425, name: "Durotan", slug: "durotan", region: "EU" },
  { id: 426, name: "Echsenkessel", slug: "echsenkessel", region: "EU" },
  { id: 427, name: "Eredar", slug: "eredar", region: "EU" },
  {
    id: 428,
    name: "Festung der Stürme",
    slug: "festung-der-stürme",
    region: "EU",
  },
  { id: 429, name: "Forscherliga", slug: "forscherliga", region: "EU" },
  { id: 430, name: "Frostmourne", slug: "frostmourne", region: "EU" },
  { id: 431, name: "Frostwolf", slug: "frostwolf", region: "EU" },
  { id: 432, name: "Garrosh", slug: "garrosh", region: "EU" },
  { id: 433, name: "Gilneas", slug: "gilneas", region: "EU" },
  { id: 434, name: "Gorgonnash", slug: "gorgonnash", region: "EU" },
  { id: 435, name: "Gul'dan", slug: "guldan", region: "EU" },
  { id: 436, name: "Kargath", slug: "kargath", region: "EU" },
  { id: 437, name: "Kel'Thuzad", slug: "kelthuzad", region: "EU" },
  { id: 438, name: "Khaz'goroth", slug: "khazgoroth", region: "EU" },
  { id: 439, name: "Kil'jaeden", slug: "kiljaeden", region: "EU" },
  { id: 440, name: "Krag'jin", slug: "kragjin", region: "EU" },
  {
    id: 441,
    name: "Kult der Verdammten",
    slug: "kult-der-verdammten",
    region: "EU",
  },
  { id: 442, name: "Lordaeron", slug: "lordaeron", region: "EU" },
  { id: 443, name: "Lothar", slug: "lothar", region: "EU" },
  { id: 444, name: "Madmortem", slug: "madmortem", region: "EU" },
  { id: 445, name: "Mal'Ganis", slug: "malganis", region: "EU" },
  { id: 446, name: "Malfurion", slug: "malfurion", region: "EU" },
  { id: 447, name: "Malorne", slug: "malorne", region: "EU" },
  { id: 448, name: "Malygos", slug: "malygos", region: "EU" },
  { id: 449, name: "Mannoroth", slug: "mannoroth", region: "EU" },
  { id: 450, name: "Mug'thol", slug: "mugthol", region: "EU" },
  { id: 451, name: "Nathrezim", slug: "nathrezim", region: "EU" },
  { id: 452, name: "Nazjatar", slug: "nazjatar", region: "EU" },
  { id: 453, name: "Nefarian", slug: "nefarian", region: "EU" },
  { id: 454, name: "Nera'thor", slug: "nerathor", region: "EU" },
  { id: 455, name: "Nethersturm", slug: "nethersturm", region: "EU" },
  { id: 456, name: "Norgannon", slug: "norgannon", region: "EU" },
  { id: 457, name: "Nozdormu", slug: "nozdormu", region: "EU" },
  { id: 458, name: "Onyxia", slug: "onyxia", region: "EU" },
  { id: 459, name: "Perenolde", slug: "perenolde", region: "EU" },
  { id: 460, name: "Proudmoore", slug: "proudmoore", region: "EU" },
  { id: 461, name: "Rajaxx", slug: "rajaxx", region: "EU" },
  { id: 462, name: "Rexxar", slug: "rexxar", region: "EU" },
  { id: 463, name: "Sen'jin", slug: "senjin", region: "EU" },
  { id: 464, name: "Shattrath", slug: "shattrath", region: "EU" },
  { id: 465, name: "Taerar", slug: "taerar", region: "EU" },
  { id: 466, name: "Teldrassil", slug: "teldrassil", region: "EU" },
  { id: 467, name: "Terrordar", slug: "terrordar", region: "EU" },
  { id: 468, name: "Theradras", slug: "theradras", region: "EU" },
  { id: 469, name: "Thrall", slug: "thrall", region: "EU" },
  { id: 470, name: "Tichondrius", slug: "tichondrius", region: "EU" },
  { id: 471, name: "Tirion", slug: "tirion", region: "EU" },
  { id: 472, name: "Todeswache", slug: "todeswache", region: "EU" },
  { id: 473, name: "Ulduar", slug: "ulduar", region: "EU" },
  { id: 474, name: "Un'Goro", slug: "ungoro", region: "EU" },
  { id: 475, name: "Vek'lor", slug: "veklor", region: "EU" },
  { id: 476, name: "Wrathbringer", slug: "wrathbringer", region: "EU" },
  { id: 477, name: "Ysera", slug: "ysera", region: "EU" },
  {
    id: 478,
    name: "Zirkel des Cenarius",
    slug: "zirkel-des-cenarius",
    region: "EU",
  },
  { id: 479, name: "Zuluhed", slug: "zuluhed", region: "EU" },

  // Italian Realms
  { id: 480, name: "Nemesis", slug: "nemesis", region: "EU" },
  {
    id: 481,
    name: "Pozzo dell'Eternità",
    slug: "pozzo-delleternità",
    region: "EU",
  },

  // Portuguese Realms
  { id: 482, name: "Aggra (Português)", slug: "aggra-português", region: "EU" },

  // Russian Realms
  { id: 483, name: "Азурегос", slug: "azuregos", region: "EU" },
  { id: 484, name: "Борейская тундра", slug: "borean-tundra", region: "EU" },
  { id: 485, name: "Вечная Песня", slug: "eversong", region: "EU" },
  { id: 486, name: "Галакронд", slug: "galakrond", region: "EU" },
  { id: 487, name: "Голдринн", slug: "goldrinn", region: "EU" },
  { id: 488, name: "Гордунни", slug: "gordunni", region: "EU" },
  { id: 489, name: "Гром", slug: "grom", region: "EU" },
  { id: 490, name: "Дракономор", slug: "fordragon", region: "EU" },
  { id: 491, name: "Король-лич", slug: "lich-king", region: "EU" },
  { id: 492, name: "Пиратская бухта", slug: "booty-bay", region: "EU" },
  { id: 493, name: "Подземье", slug: "deepholm", region: "EU" },
  { id: 494, name: "Разувий", slug: "razuvious", region: "EU" },
  { id: 495, name: "Ревущий фьорд", slug: "howling-fjord", region: "EU" },
  { id: 496, name: "Свежеватель Душ", slug: "soulflayer", region: "EU" },
  { id: 497, name: "Седогрив", slug: "greymane", region: "EU" },
  { id: 498, name: "Страж Смерти", slug: "deathguard", region: "EU" },
  { id: 499, name: "Термоштепсель", slug: "thermaplugg", region: "EU" },
  { id: 500, name: "Ткач Смерти", slug: "deathweaver", region: "EU" },
  { id: 501, name: "Черный Шрам", slug: "blackscar", region: "EU" },
  { id: 502, name: "Ясеневый лес", slug: "ashenvale", region: "EU" },

  // Spanish Realms
  { id: 503, name: "C'Thun", slug: "cthun", region: "EU" },
  { id: 504, name: "Colinas Pardas", slug: "colinas-pardas", region: "EU" },
  { id: 505, name: "Dun Modr", slug: "dun-modr", region: "EU" },
  { id: 506, name: "Exodar", slug: "exodar", region: "EU" },
  { id: 507, name: "Los Errantes", slug: "los-errantes", region: "EU" },
  { id: 508, name: "Minahonda", slug: "minahonda", region: "EU" },
  { id: 509, name: "Sanguino", slug: "sanguino", region: "EU" },
  { id: 510, name: "Shen'dralar", slug: "shendralar", region: "EU" },
  { id: 511, name: "Tyrande", slug: "tyrande", region: "EU" },
  { id: 512, name: "Uldum", slug: "uldum", region: "EU" },
  { id: 513, name: "Zul'jin", slug: "zuljin", region: "EU" },
];
