export const usRealms = [
  // United States Realms
  { id: 1, name: "Aegwynn", slug: "aegwynn", region: "US" },
  { id: 2, name: "Aerie Peak", slug: "aerie-peak", region: "US" },
  { id: 3, name: "Agamaggan", slug: "agamaggan", region: "US" },
  { id: 4, name: "Aggramar", slug: "aggramar", region: "US" },
  { id: 5, name: "Akama", slug: "akama", region: "US" },
  { id: 6, name: "Alexstrasza", slug: "alexstrasza", region: "US" },
  { id: 7, name: "Alleria", slug: "alleria", region: "US" },
  { id: 8, name: "Altar of Storms", slug: "altar-of-storms", region: "US" },
  { id: 9, name: "Alterac Mountains", slug: "alterac-mountains", region: "US" },
  { id: 11, name: "Andorhal", slug: "andorhal", region: "US" },
  { id: 12, name: "Anetheron", slug: "anetheron", region: "US" },
  { id: 13, name: "Antonidas", slug: "antonidas", region: "US" },
  { id: 14, name: "Anub'arak", slug: "anubarak", region: "US" },
  { id: 15, name: "Anvilmar", slug: "anvilmar", region: "US" },
  { id: 16, name: "Arathor", slug: "arathor", region: "US" },
  { id: 17, name: "Archimonde", slug: "archimonde", region: "US" },
  { id: 18, name: "Area 52", slug: "area-52", region: "US" },
  { id: 19, name: "Argent Dawn", slug: "argent-dawn", region: "US" },
  { id: 20, name: "Arthas", slug: "arthas", region: "US" },
  { id: 21, name: "Arygos", slug: "arygos", region: "US" },
  { id: 22, name: "Auchindoun", slug: "auchindoun", region: "US" },
  { id: 23, name: "Azgalor", slug: "azgalor", region: "US" },
  { id: 24, name: "Azjol-Nerub", slug: "azjolnerub", region: "US" },
  { id: 25, name: "Azralon", slug: "azralon", region: "US" },
  { id: 26, name: "Azshara", slug: "azshara", region: "US" },
  { id: 27, name: "Azuremyst", slug: "azuremyst", region: "US" },
  { id: 28, name: "Baelgun", slug: "baelgun", region: "US" },
  { id: 29, name: "Balnazzar", slug: "balnazzar", region: "US" },
  {
    id: 31,
    name: "Black Dragonflight",
    slug: "black-dragonflight",
    region: "US",
  },
  { id: 32, name: "Blackhand", slug: "blackhand", region: "US" },
  { id: 33, name: "Blackrock", slug: "blackrock", region: "US" },
  {
    id: 34,
    name: "Blackwater Raiders",
    slug: "blackwater-raiders",
    region: "US",
  },
  { id: 35, name: "Blackwing Lair", slug: "blackwing-lair", region: "US" },
  { id: 36, name: "Blade's Edge", slug: "blades-edge", region: "US" },
  { id: 37, name: "Bladefist", slug: "bladefist", region: "US" },
  { id: 38, name: "Bleeding Hollow", slug: "bleeding-hollow", region: "US" },
  { id: 39, name: "Blood Furnace", slug: "blood-furnace", region: "US" },
  { id: 40, name: "Bloodhoof", slug: "bloodhoof", region: "US" },
  { id: 41, name: "Bloodscalp", slug: "bloodscalp", region: "US" },
  { id: 42, name: "Bonechewer", slug: "bonechewer", region: "US" },
  { id: 43, name: "Borean Tundra", slug: "borean-tundra", region: "US" },
  { id: 44, name: "Boulderfist", slug: "boulderfist", region: "US" },
  { id: 45, name: "Bronzebeard", slug: "bronzebeard", region: "US" },
  { id: 46, name: "Burning Blade", slug: "burning-blade", region: "US" },
  { id: 47, name: "Burning Legion", slug: "burning-legion", region: "US" },
  { id: 49, name: "Cairne", slug: "cairne", region: "US" },
  { id: 50, name: "Cenarion Circle", slug: "cenarion-circle", region: "US" },
  { id: 51, name: "Cenarius", slug: "cenarius", region: "US" },
  { id: 52, name: "Cho'gall", slug: "chogall", region: "US" },
  { id: 53, name: "Chromaggus", slug: "chromaggus", region: "US" },
  { id: 54, name: "Coilfang", slug: "coilfang", region: "US" },
  { id: 55, name: "Crushridge", slug: "crushridge", region: "US" },
  { id: 56, name: "Daggerspine", slug: "daggerspine", region: "US" },
  { id: 57, name: "Dalaran", slug: "dalaran", region: "US" },
  { id: 58, name: "Dalvengyr", slug: "dalvengyr", region: "US" },
  { id: 59, name: "Dark Iron", slug: "dark-iron", region: "US" },
  { id: 60, name: "Darkspear", slug: "darkspear", region: "US" },
  { id: 61, name: "Darrowmere", slug: "darrowmere", region: "US" },
  { id: 63, name: "Dawnbringer", slug: "dawnbringer", region: "US" },
  { id: 64, name: "Deathwing", slug: "deathwing", region: "US" },
  { id: 65, name: "Demon Soul", slug: "demon-soul", region: "US" },
  { id: 66, name: "Dentarg", slug: "dentarg", region: "US" },
  { id: 67, name: "Destromath", slug: "destromath", region: "US" },
  { id: 68, name: "Dethecus", slug: "dethecus", region: "US" },
  { id: 69, name: "Detheroc", slug: "detheroc", region: "US" },
  { id: 70, name: "Doomhammer", slug: "doomhammer", region: "US" },
  { id: 71, name: "Draenor", slug: "draenor", region: "US" },
  { id: 72, name: "Dragonblight", slug: "dragonblight", region: "US" },
  { id: 73, name: "Dragonmaw", slug: "dragonmaw", region: "US" },
  { id: 74, name: "Drak'Tharon", slug: "draktharon", region: "US" },
  { id: 75, name: "Drak'thul", slug: "drakthul", region: "US" },
  { id: 76, name: "Draka", slug: "draka", region: "US" },
  { id: 77, name: "Drakkari", slug: "drakkari", region: "US" },
  { id: 79, name: "Drenden", slug: "drenden", region: "US" },
  { id: 80, name: "Dunemaul", slug: "dunemaul", region: "US" },
  { id: 81, name: "Durotan", slug: "durotan", region: "US" },
  { id: 82, name: "Duskwood", slug: "duskwood", region: "US" },
  { id: 83, name: "Earthen Ring", slug: "earthen-ring", region: "US" },
  { id: 84, name: "Echo Isles", slug: "echo-isles", region: "US" },
  { id: 85, name: "Eitrigg", slug: "eitrigg", region: "US" },
  { id: 86, name: "Eldre'Thalas", slug: "eldrethalas", region: "US" },
  { id: 87, name: "Elune", slug: "elune", region: "US" },
  { id: 88, name: "Emerald Dream", slug: "emerald-dream", region: "US" },
  { id: 89, name: "Eonar", slug: "eonar", region: "US" },
  { id: 90, name: "Eredar", slug: "eredar", region: "US" },
  { id: 91, name: "Executus", slug: "executus", region: "US" },
  { id: 92, name: "Exodar", slug: "exodar", region: "US" },
  { id: 93, name: "Farstriders", slug: "farstriders", region: "US" },
  { id: 94, name: "Feathermoon", slug: "feathermoon", region: "US" },
  { id: 95, name: "Fenris", slug: "fenris", region: "US" },
  { id: 96, name: "Firetree", slug: "firetree", region: "US" },
  { id: 97, name: "Fizzcrank", slug: "fizzcrank", region: "US" },
  { id: 98, name: "Frostmane", slug: "frostmane", region: "US" },
  { id: 100, name: "Frostwolf", slug: "frostwolf", region: "US" },
  { id: 101, name: "Galakrond", slug: "galakrond", region: "US" },
  { id: 102, name: "Gallywix", slug: "gallywix", region: "US" },
  { id: 103, name: "Garithos", slug: "garithos", region: "US" },
  { id: 104, name: "Garona", slug: "garona", region: "US" },
  { id: 105, name: "Garrosh", slug: "garrosh", region: "US" },
  { id: 106, name: "Ghostlands", slug: "ghostlands", region: "US" },
  {
    id: 107,
    name: "Gilneas",
    slug: "gilneas",
    region: "US",
  },
  { id: 108, name: "Gnomeregan", slug: "gnomeregan", region: "US" },
  { id: 109, name: "Goldrinn", slug: "goldrinn", region: "US" },
  { id: 110, name: "Gorefiend", slug: "gorefiend", region: "US" },
  { id: 111, name: "Gorgonnash", slug: "gorgonnash", region: "US" },
  {
    id: 112,
    name: "Greymane",
    slug: "greymane",
    region: "US",
  },
  { id: 113, name: "Grizzly Hills", slug: "grizzly-hills", region: "US" },
  { id: 114, name: "Gul'dan", slug: "guldan", region: "US" },
  { id: 115, name: "Gundrak", slug: "gundrak", region: "US" },
  { id: 116, name: "Gurubashi", slug: "gurubashi", region: "US" },
  { id: 117, name: "Hakkar", slug: "hakkar", region: "US" },
  { id: 118, name: "Haomarush", slug: "haomarush", region: "US" },
  {
    id: 119,
    name: "Hellscream",
    slug: "hellscream",
    region: "US",
  },
  { id: 120, name: "Hydraxis", slug: "hydraxis", region: "US" },
  { id: 121, name: "Hyjal", slug: "hyjal", region: "US" },
  { id: 122, name: "Icecrown", slug: "icecrown", region: "US" },
  { id: 123, name: "Illidan", slug: "illidan", region: "US" },
  {
    id: 124,
    name: "Jaedenar",
    slug: "jaedenar",
    region: "US",
  },
  { id: 125, name: "Jubei'Thos", slug: "jubeithos", region: "US" },
  { id: 126, name: "Kael'thas", slug: "kaelthas", region: "US" },
  { id: 127, name: "Kalecgos", slug: "kalecgos", region: "US" },
  { id: 128, name: "Kargath", slug: "kargath", region: "US" },
  { id: 129, name: "Kel'Thuzad", slug: "kelthuzad", region: "US" },
  { id: 130, name: "Khadgar", slug: "khadgar", region: "US" },
  { id: 131, name: "Khaz Modan", slug: "khazmodan", region: "US" },
  { id: 132, name: "Khaz'goroth", slug: "khazgoroth", region: "US" },
  { id: 133, name: "Kil'jaeden", slug: "kiljaeden", region: "US" },
  { id: 134, name: "Kilrogg", slug: "kilrogg", region: "US" },
  { id: 135, name: "Kirin Tor", slug: "kirin-tor", region: "US" },
  { id: 136, name: "Korgath", slug: "korgath", region: "US" },
  { id: 137, name: "Korialstrasz", slug: "korialstrasz", region: "US" },
  { id: 138, name: "Kul Tiras", slug: "kul-tiras", region: "US" },
  { id: 139, name: "Laughing Skull", slug: "laughing-skull", region: "US" },
  { id: 140, name: "Lethon", slug: "lethon", region: "US" },
  { id: 141, name: "Lightbringer", slug: "lightbringer", region: "US" },
  {
    id: 142,
    name: "Lightning's Blade",
    slug: "lightnings-blade",
    region: "US",
  },
  { id: 143, name: "Lightninghoof", slug: "lightninghoof", region: "US" },
  { id: 144, name: "Llane", slug: "llane", region: "US" },
  { id: 145, name: "Lothar", slug: "lothar", region: "US" },
  { id: 146, name: "Madoran", slug: "madoran", region: "US" },
  { id: 147, name: "Maelstrom", slug: "maelstrom", region: "US" },
  { id: 148, name: "Magtheridon", slug: "magtheridon", region: "US" },
  { id: 149, name: "Maiev", slug: "maiev", region: "US" },
  { id: 150, name: "Mal'Ganis", slug: "malganis", region: "US" },
  { id: 151, name: "Malfurion", slug: "malfurion", region: "US" },
  { id: 152, name: "Malorne", slug: "malorne", region: "US" },
  { id: 153, name: "Malygos", slug: "malygos", region: "US" },
  { id: 154, name: "Mannoroth", slug: "mannoroth", region: "US" },
  { id: 155, name: "Medivh", slug: "medivh", region: "US" },
  { id: 156, name: "Misha", slug: "misha", region: "US" },
  { id: 157, name: "Mok'Nathal", slug: "moknathal", region: "US" },

  {
    id: 158,
    name: "Moon Guard",
    slug: "moon-guard",
    region: "US",
  },
  {
    id: 159,
    name: "Moonrunner",
    slug: "moonrunner",
    region: "US",
  },
  {
    id: 160,
    name: "Mug'thol",
    slug: "mugthol",
    region: "US",
  },
  {
    id: 161,
    name: "Muradin",
    slug: "muradin",
    region: "US",
  },
  {
    id: 162,
    name: "Nagrand",
    slug: "nagrand",
    region: "US",
  },
  {
    id: 163,
    name: "Nathrezim",
    slug: "nathrezim",
    region: "US",
  },
  {
    id: 164,
    name: "Nazgrel",
    slug: "nazgrel",
    region: "US",
  },
  {
    id: 165,
    name: "Nazjatar",
    slug: "nazjatar",
    region: "US",
  },
  {
    id: 166,
    name: "Nemesis",
    slug: "nemesis",
    region: "US",
  },
  {
    id: 167,
    name: "Ner'zhul",
    slug: "nerzhul",
    region: "US",
  },
  {
    id: 168,
    name: "Nesingwary",
    slug: "nesingwary",
    region: "US",
  },
  {
    id: 169,
    name: "Nordrassil",
    slug: "nordrassil",
    region: "US",
  },
  {
    id: 170,
    name: "Norgannon",
    slug: "norgannon",
    region: "US",
  },
  {
    id: 171,
    name: "Onyxia",
    slug: "onyxia",
    region: "US",
  },
  {
    id: 172,
    name: "Perenolde",
    slug: "perenolde",
    region: "US",
  },
  {
    id: 173,
    name: "Proudmoore",
    slug: "proudmoore",
    region: "US",
  },
  {
    id: 174,
    name: "Quel'Thalas",
    slug: "quelthalas",
    region: "US",
  },
  {
    id: 175,
    name: "Quel'dorei",
    slug: "queldorei",
    region: "US",
  },
  {
    id: 176,
    name: "Ragnaros",
    slug: "ragnaros",
    region: "US",
  },
  {
    id: 177,
    name: "Ravencrest",
    slug: "ravencrest",
    region: "US",
  },
  {
    id: 178,
    name: "Ravenholdt",
    slug: "ravenholdt",
    region: "US",
  },
  {
    id: 179,
    name: "Rexxar",
    slug: "rexxar",
    region: "US",
  },
  {
    id: 180,
    name: "Rivendare",
    slug: "rivendare",
    region: "US",
  },
  {
    id: 181,
    name: "Runetotem",
    slug: "runetotem",
    region: "US",
  },
  {
    id: 182,
    name: "Sargeras",
    slug: "sargeras",
    region: "US",
  },
  {
    id: 183,
    name: "Saurfang",
    slug: "saurfang",
    region: "US",
  },
  {
    id: 184,
    name: "Scarlet Crusade",
    slug: "scarlet-crusade",
    region: "US",
  },
  {
    id: 185,
    name: "Scilla",
    slug: "scilla",
    region: "US",
  },
  {
    id: 186,
    name: "Sen'jin",
    slug: "senjin",
    region: "US",
  },
  {
    id: 187,
    name: "Sentinels",
    slug: "sentinels",
    region: "US",
  },
  {
    id: 188,
    name: "Shadow Council",
    slug: "shadow-council",
    region: "US",
  },
  {
    id: 189,
    name: "Shadowmoon",
    slug: "shadowmoon",
    region: "US",
  },
  {
    id: 190,
    name: "Shadowsong",
    slug: "shadowsong",
    region: "US",
  },
  {
    id: 191,
    name: "Shandris",
    slug: "shandris",
    region: "US",
  },
  {
    id: 192,
    name: "Shattered Halls",
    slug: "shattered-halls",
    region: "US",
  },
  {
    id: 193,
    name: "Shattered Hand",
    slug: "shattered-hand",
    region: "US",
  },
  {
    id: 194,
    name: "Shu'halo",
    slug: "shuhalo",
    region: "US",
  },
  {
    id: 195,
    name: "Silver Hand",
    slug: "silver-hand",
    region: "US",
  },
  {
    id: 196,
    name: "Silvermoon",
    slug: "silvermoon",
    region: "US",
  },
  {
    id: 197,
    name: "Sisters of Elune",
    slug: "sisters-of-elune",
    region: "US",
  },
  {
    id: 198,
    name: "Skullcrusher",
    slug: "skullcrusher",
    region: "US",
  },
  {
    id: 199,
    name: "Skywall",
    slug: "skywall",
    region: "US",
  },
  {
    id: 200,
    name: "Smolderthorn",
    slug: "smolderthorn",
    region: "US",
  },
  {
    id: 201,
    name: "Spinebreaker",
    slug: "spinebreaker",
    region: "US",
  },
  {
    id: 202,
    name: "Spirestone",
    slug: "spirestone",
    region: "US",
  },
  {
    id: 203,
    name: "Staghelm",
    slug: "staghelm",
    region: "US",
  },
  {
    id: 204,
    name: "Steamwheedle Cartel",
    slug: "steamwheedle-cartel",
    region: "US",
  },
  {
    id: 205,
    name: "Stonemaul",
    slug: "stonemaul",
    region: "US",
  },
  {
    id: 206,
    name: "Stormrage",
    slug: "stormrage",
    region: "US",
  },
  {
    id: 207,
    name: "Stormreaver",
    slug: "stormreaver",
    region: "US",
  },
  {
    id: 208,
    name: "Stormscale",
    slug: "stormscale",
    region: "US",
  },
  {
    id: 209,
    name: "Suramar",
    slug: "suramar",
    region: "US",
  },
  {
    id: 210,
    name: "Tanaris",
    slug: "tanaris",
    region: "US",
  },
  {
    id: 211,
    name: "Terenas",
    slug: "terenas",
    region: "US",
  },

  {
    id: 212,
    name: "Terokkar",
    slug: "terokkar",
    region: "US",
  },
  {
    id: 214,
    name: "The Forgotten Coast",
    slug: "the-forgotten-coast",
    region: "US",
  },
  {
    id: 215,
    name: "The Scryers",
    slug: "the-scryers",
    region: "US",
  },
  {
    id: 216,
    name: "The Underbog",
    slug: "the-underbog",
    region: "US",
  },
  {
    id: 217,
    name: "The Venture Co",
    slug: "the-venture-co",
    region: "US",
  },
  {
    id: 218,
    name: "Thorium Brotherhood",
    slug: "thorium-brotherhood",
    region: "US",
  },
  {
    id: 219,
    name: "Thrall",
    slug: "thrall",
    region: "US",
  },
  {
    id: 220,
    name: "Thunderhorn",
    slug: "thunderhorn",
    region: "US",
  },
  {
    id: 221,
    name: "Thunderlord",
    slug: "thunderlord",
    region: "US",
  },
  {
    id: 222,
    name: "Tichondrius",
    slug: "tichondrius",
    region: "US",
  },
  {
    id: 223,
    name: "Tol Barad",
    slug: "tol-barad",
    region: "US",
  },
  {
    id: 224,
    name: "Tortheldrin",
    slug: "tortheldrin",
    region: "US",
  },
  {
    id: 225,
    name: "Trollbane",
    slug: "trollbane",
    region: "US",
  },
  {
    id: 226,
    name: "Turalyon",
    slug: "turalyon",
    region: "US",
  },
  {
    id: 227,
    name: "Twisting Nether",
    slug: "twisting-nether",
    region: "US",
  },
  {
    id: 228,
    name: "Uldaman",
    slug: "uldaman",
    region: "US",
  },
  {
    id: 229,
    name: "Uldum",
    slug: "uldum",
    region: "US",
  },
  {
    id: 230,
    name: "Undermine",
    slug: "undermine",
    region: "US",
  },
  {
    id: 231,
    name: "Ursin",
    slug: "ursin",
    region: "US",
  },
  {
    id: 232,
    name: "Uther",
    slug: "uther",
    region: "US",
  },
  {
    id: 233,
    name: "Vashj",
    slug: "vashj",
    region: "US",
  },
  {
    id: 234,
    name: "Vek'nilash",
    slug: "veknilash",
    region: "US",
  },
  {
    id: 235,
    name: "Velen",
    slug: "velen",
    region: "US",
  },
  {
    id: 236,
    name: "Warsong",
    slug: "warsong",
    region: "US",
  },
  {
    id: 237,
    name: "Whisperwind",
    slug: "whisperwind",
    region: "US",
  },
  {
    id: 238,
    name: "Wildhammer",
    slug: "wildhammer",
    region: "US",
  },
  {
    id: 239,
    name: "Windrunner",
    slug: "windrunner",
    region: "US",
  },
  {
    id: 240,
    name: "Winterhoof",
    slug: "winterhoof",
    region: "US",
  },
  {
    id: 241,
    name: "Wyrmrest Accord",
    slug: "wyrmrest-accord",
    region: "US",
  },
  {
    id: 242,
    name: "Ysera",
    slug: "ysera",
    region: "US",
  },
  {
    id: 243,
    name: "Ysondre",
    slug: "ysondre",
    region: "US",
  },
  {
    id: 244,
    name: "Zangarmarsh",
    slug: "zangarmarsh",
    region: "US",
  },
  {
    id: 245,
    name: "Zul'jin",
    slug: "zuljin",
    region: "US",
  },
  {
    id: 246,
    name: "Zuluhed",
    slug: "zuluhed",
    region: "US",
  },
  {
    id: 916,
    name: "Xavius",
    slug: "xavius",
    region: "US",
  },

  // Oceanic Realms
  { id: 10, name: "Aman'Thul", slug: "amanthul", region: "US" },
  { id: 30, name: "Barthilas", slug: "barthilas", region: "US" },
  { id: 48, name: "Caelestrasz", slug: "caelestrasz", region: "US" },
  { id: 62, name: "Dath'Remar", slug: "dathremar", region: "US" },
  { id: 78, name: "Dreadmaul", slug: "dreadmaul", region: "US" },
  { id: 99, name: "Frostmourne", slug: "frostmourne", region: "US" },
  { id: 115, name: "Gundrak", slug: "gundrak", region: "US" },
  { id: 125, name: "Jubei'Thos", slug: "jubeithos", region: "US" },
  { id: 132, name: "Khaz'goroth", slug: "khazgoroth", region: "US" },
  { id: 162, name: "Nagrand", slug: "nagrand", region: "US" },
  { id: 183, name: "Saurfang", slug: "saurfang", region: "US" },
  { id: 213, name: "Thaurissan", slug: "thaurissan", region: "US" },
];
