global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "backend"
    scrape_interval: 1000s
    metrics_path: "/metrics"
    static_configs:
      - targets: ["backend:8080"]

  - job_name: "temporal"
    scrape_interval: 1000s
    metrics_path: "/metrics"
    static_configs:
      - targets: ["temporal:9090"]

  - job_name: "temporal-worker"
    scrape_interval: 1000s
    metrics_path: "/metrics"
    static_configs:
      - targets: ["temporal-worker:9090"]

  - job_name: "report-test"
    scrape_interval: 1000s
    metrics_path: "/metrics"
    static_configs:
      - targets: ["report-test:9090"]
