rankings:
  max_rankings_per_spec: 1500
  update_interval: 168h # 7 days

worker:
  num_workers: 3
  retry_attempts: 3
  retry_delay: 5s
  batch_size: 100
  request_delay: 500ms

specs:
  # Priest
  - class_name: "Priest"
    spec_name: "Discipline"
  - class_name: "Priest"
    spec_name: "Holy"
  - class_name: "Priest"
    spec_name: "Shadow"

  # Death Knight
  - class_name: "DeathKnight"
    spec_name: "Blood"
  - class_name: "DeathKnight"
    spec_name: "Frost"
  - class_name: "DeathKnight"
    spec_name: "Unholy"

  # Druid
  - class_name: "Druid"
    spec_name: "Balance"
  - class_name: "Druid"
    spec_name: "Feral"
  - class_name: "Druid"
    spec_name: "Guardian"
  - class_name: "Druid"
    spec_name: "Restoration"

  # Hunter
  - class_name: "Hunter"
    spec_name: "BeastMastery"
  - class_name: "Hunter"
    spec_name: "Marksmanship"
  - class_name: "Hunter"
    spec_name: "Survival"

  # Mage
  - class_name: "Mage"
    spec_name: "Arcane"
  - class_name: "Mage"
    spec_name: "Fire"
  - class_name: "Mage"
    spec_name: "Frost"

  # Monk
  - class_name: "Monk"
    spec_name: "Brewmaster"
  - class_name: "Monk"
    spec_name: "Mistweaver"
  - class_name: "Monk"
    spec_name: "Windwalker"

  # Paladin
  - class_name: "Paladin"
    spec_name: "Holy"
  - class_name: "Paladin"
    spec_name: "Protection"
  - class_name: "Paladin"
    spec_name: "Retribution"

  # Rogue
  - class_name: "Rogue"
    spec_name: "Assassination"
  - class_name: "Rogue"
    spec_name: "Subtlety"
  - class_name: "Rogue"
    spec_name: "Outlaw"

  # Shaman
  - class_name: "Shaman"
    spec_name: "Elemental"
  - class_name: "Shaman"
    spec_name: "Enhancement"
  - class_name: "Shaman"
    spec_name: "Restoration"

  # Warlock
  - class_name: "Warlock"
    spec_name: "Affliction"
  - class_name: "Warlock"
    spec_name: "Demonology"
  - class_name: "Warlock"
    spec_name: "Destruction"

  # Warrior
  - class_name: "Warrior"
    spec_name: "Arms"
  - class_name: "Warrior"
    spec_name: "Fury"
  - class_name: "Warrior"
    spec_name: "Protection"

  # Demon Hunter
  - class_name: "DemonHunter"
    spec_name: "Havoc"
  - class_name: "DemonHunter"
    spec_name: "Vengeance"

  # Evoker
  - class_name: "Evoker"
    spec_name: "Devastation"
  - class_name: "Evoker"
    spec_name: "Preservation"
  - class_name: "Evoker"
    spec_name: "Augmentation"

dungeons:
  - id: 12661
    encounter_id: 12661
    name: "Cinderbrew Meadery"
    slug: "cinderbrew-meadery"
  - id: 12651
    encounter_id: 12651
    name: "Darkflame Cleft"
    slug: "darkflame-cleft"
  - id: 112098
    encounter_id: 112098
    name: "Mechagon Workshop"
    slug: "operation-mechagon-workshop"
  - id: 12773
    encounter_id: 12773
    name: "Operation: Floodgate"
    slug: "operation-floodgate"
  - id: 12649
    encounter_id: 12649
    name: "Priory of the Sacred Flame"
    slug: "priory-of-the-sacred-flame"
  - id: 61594
    encounter_id: 61594
    name: "The MOTHERLODE!!"
    slug: "the-motherlode"
  - id: 12648
    encounter_id: 12648
    name: "The Rookery"
    slug: "the-rookery"
  - id: 62293
    encounter_id: 62293
    name: "Theater of Pain"
    slug: "theater-of-pain"
